# Generated by Django 5.2.5 on 2025-08-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='gemini_response',
            new_name='model_response',
        ),
    ]
