# Generated by Django 5.2.5 on 2025-08-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_invalidated',
            field=models.BooleanField(default=True),
        ),
    ]
